# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1be085b8244d6b3c0bda5091326eaaafe9607e81b865d92ccec0aef238ae0266631792202ee457aa7403ffdec55fe6eb9a8272dc682974be1965fc04ff63879e

test:
  secret_key_base: d7e490beeeeadb5d2101732d9c4eaa63002b3349e8c94725423ab0ae1e77f4d237f162e0f14a52a1a0ce2ac81ca30bca29eb75e5a899112193f13711008d0784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
